# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
python_paths:
  # Need to place kubeflow/testing in front of kubeflow/testing so that the package can
  # be correctly located.
  - kubeflow/testing/py
  - kubeflow/kfctl/py
workflows:
  - app_dir: kubeflow/kfctl/testing/workflows
    component: unit_tests
    name: unittests
    params:
      workflowName: unittest
    job_types:
      - presubmit
      - postsubmit
      - periodic
    include_dirs:
      - config/*
      - cmd/*
      - pkg/*
      - kustomize-fns/*
      - testing/*
      - py/*
  